language: node_js
sudo: enabled
node_js:
  - "8"
# services:
#   - mssql
# before_install:
#   - mssql -e 'CREATE DATABASE mssql-i-test;'
before_script:
  - npm i pcreate
script :
  # - npm run test
  # - nyc mocha -t 120000 --server $SQLSERVER_IP --password $SQLSERVER_PASSWORD
  # - npm run build
  - pcreate test --mochapars {server: $SQLSERVER_IP, password: $SQLSERVER_PASSWORD }
  - pcreate build
after_script:
  # - npm run test-nyc 
  # - nyc mocha -t 120000 --server $SQLSERVER_IP --password $SQLSERVER_PASSWORD && nyc report --reporter=text-lcov | coveralls

cache:
  directories:
    - node_modules

deploy:
  - provider: npm
    skip_cleanup: true
    email: heifade@126.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      repo: heifade/mssql-i
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master