language: node_js
node_js:
  - "8"
# services:
#   - mssql
# before_install:
#   - mssql -e 'CREATE DATABASE mssql-i-test;'
# script :
#   - "npm test"
# after_script:
#   - "npm run test-nyc"

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: heifade@126.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: heifade/mssql-i

